apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-policy-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-policy-ctrl
  template:
    metadata:
      labels:
        name: config-policy-ctrl
    spec:
      serviceAccountName: config-policy-ctrl
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
        - name: config-policy-ctrl
          # Replace this with the built image name
          image: quay.io/open-cluster-management/config-policy-controller:1.0.0-cb5e6c92aafb0f1a1b2934df9a2a18dd71a88ac3
          command:
          - config-policy-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: calamari
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "config-policy-ctrl"